### ISSUE TITLE
exporting and importing from bolt 3 to bolt 4

### ISSUE THREAD

**Issue by twokingshq** [bobdenotter/conimex#1]
The import and export files are incompatible.
Even with minor tweaks in the yaml file it is impossible to import everythingto bolt 4
Making this extentsion support the export from bolt 3 would resolve this isseu

**Comment by michaelborn** [comment]
@twokingshq Do you have any specific examples of field types or data which is not compatible?

For myself, I see the specific error noted in issue #27 . If we don't have a specific example, I suggest closing this ticket as a duplicate of #27.

**Comment by bobdenotter** [comment]
This is an old ticket, indeed. Let's close this one. 🙏

**Comment by michaelborn** [comment]
Lol - I didn't notice the "Two kings HQ" username. I see what's going on.
