### ISSUE TITLE
Unexpected output for relations

### ISSUE THREAD

**Issue by simongroenewolt** [bobdenotter/conimex#52]
When exporting using conimex version 2.0.7 (but also earlier versions) in a Bolt 5.1 (upgraded from 4.x) project I'm seeing unexpected output for relations:

```
        relations:
            "\0*\0items": {  }
            "\0*\0escapeWhenCastingToString": {  }
```

**Comment by simongroenewolt** [comment]
It looks like the output is related to the result of https://github.com/bobdenotter/conimex/blob/e8e6d7e2ef88e87dcd6e4e481783217c90740f1f/src/Export.php#L103 returning a Tightenco\Collect\Support\Collection instead of an array.

**Comment by simongroenewolt** [comment]
@sablonier which version of Bolt are you using?

**Comment by sablonier** [comment]
* Bolt version: 5.1.2
* PHP version: 8.1.1
* Symfony version: v5.4.2

**Comment by simongroenewolt** [comment]
I've made a change that should fix the issue. https://github.com/bobdenotter/conimex/pull/54

**Comment by sablonier** [comment]
Here it works with this fix now, thank you

**Comment by simongroenewolt** [comment]
Closing, I think this one is fixed.
